<?php
/**
 * FormIt
 *
 * Copyright 2009-2012 by Shaun McCormick <shaun@modx.com>
 *
 * FormIt is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option) any
 * later version.
 *
 * FormIt is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * FormIt; if not, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA
 *
 * @package formit
 */
/**
 * Array of countries
 * @package formit
 * @author Treigh PM
 */
 return array (
   'AF' => 'Afghanistan',
   'ZA' => 'Afrique du Sud',
   'AL' => 'Albanie',
   'DZ' => 'Alg&eacute;rie',
   'DE' => 'Allemagne',
   'AD' => 'Andorre',
   'AO' => 'Angola',
   'AI' => 'Anguilla',
   'AQ' => 'Antarctique',
   'AG' => 'Antigua-et-Barbuda',
   'SA' => 'Arabie saoudite',
   'AR' => 'Argentine',
   'AM' => 'Arm&eacute;nie',
   'AW' => 'Aruba',
   'AU' => 'Australie',
   'AT' => 'Autriche',
   'AZ' => 'Azerba&iuml;djan',
   'BS' => 'Bahamas',
   'BH' => 'Bahre&iuml;n',
   'BD' => 'Bangladesh',
   'BB' => 'Barbade',
   'BE' => 'Belgique',
   'BZ' => 'Belize',
   'BJ' => 'B&eacute;nin',
   'BM' => 'Bermudes',
   'BT' => 'Bhoutan',
   'BY' => 'Bi&eacute;lorussie',
   'BO' => 'Bolivie',
   'BA' => 'Bosnie-Herz&eacute;govine',
   'BW' => 'Botswana',
   'BR' => 'Br&eacute;sil',
   'BN' => 'Brun&eacute;i Darussalam',
   'BG' => 'Bulgarie',
   'BF' => 'Burkina Faso',
   'BI' => 'Burundi',
   'KH' => 'Cambodge',
   'CM' => 'Cameroun',
   'CA' => 'Canada',
   'CV' => 'Cap-Vert',
   'EA' => 'Ceuta et Melilla',
   'CL' => 'Chili',
   'CN' => 'Chine',
   'CY' => 'Chypre',
   'CO' => 'Colombie',
   'KM' => 'Comores',
   'CG' => 'Congo-Brazzaville',
   'CD' => 'Congo-Kinshasa',
   'KP' => 'Cor&eacute;e du Nord',
   'KR' => 'Cor&eacute;e du Sud',
   'CR' => 'Costa Rica',
   'CI' => 'C&ocirc;te d’Ivoire',
   'HR' => 'Croatie',
   'CU' => 'Cuba',
   'CW' => 'Cura&ccedil;ao',
   'DK' => 'Danemark',
   'DG' => 'Diego Garcia',
   'DJ' => 'Djibouti',
   'DM' => 'Dominique',
   'EG' => '&Eacute;gypte',
   'SV' => 'El Salvador',
   'AE' => '&Eacute;mirats arabes unis',
   'EC' => '&Eacute;quateur',
   'ER' => '&Eacute;rythr&eacute;e',
   'ES' => 'Espagne',
   'EE' => 'Estonie',
   'VA' => '&Eacute;tat de la Cit&eacute; du Vatican',
   'FM' => '&Eacute;tats f&eacute;d&eacute;r&eacute;s de Micron&eacute;sie',
   'US' => '&Eacute;tats-Unis',
   'ET' => '&Eacute;thiopie',
   'FJ' => 'Fidji',
   'FI' => 'Finlande',
   'FR' => 'France',
   'GA' => 'Gabon',
   'GM' => 'Gambie',
   'GE' => 'G&eacute;orgie',
   'GH' => 'Ghana',
   'GI' => 'Gibraltar',
   'GR' => 'Gr&egrave;ce',
   'GD' => 'Grenade',
   'GL' => 'Groenland',
   'GP' => 'Guadeloupe',
   'GU' => 'Guam',
   'GT' => 'Guatemala',
   'GG' => 'Guernesey',
   'GN' => 'Guin&eacute;e',
   'GQ' => 'Guin&eacute;e &eacute;quatoriale',
   'GW' => 'Guin&eacute;e-Bissau',
   'GY' => 'Guyana',
   'GF' => 'Guyane fran&ccedil;aise',
   'HT' => 'Ha&iuml;ti',
   'HN' => 'Honduras',
   'HU' => 'Hongrie',
   'CX' => '&Icirc;le Christmas',
   'AC' => '&Icirc;le de l’Ascension',
   'IM' => '&Icirc;le de Man',
   'NF' => '&Icirc;le Norfolk',
   'AX' => '&Icirc;les &Aring;land',
   'KY' => '&Icirc;les Ca&iuml;mans',
   'IC' => '&Icirc;les Canaries',
   'CC' => '&Icirc;les Cocos',
   'CK' => '&Icirc;les Cook',
   'FO' => '&Icirc;les F&eacute;ro&eacute;',
   'GS' => '&Icirc;les G&eacute;orgie du Sud et Sandwich du Sud',
   'FK' => '&Icirc;les Malouines',
   'MP' => '&Icirc;les Mariannes du Nord',
   'MH' => '&Icirc;les Marshall',
   'UM' => '&Icirc;les mineures &eacute;loign&eacute;es des &eacute;tats-Unis',
   'SB' => '&Icirc;les Salomon',
   'TC' => '&Icirc;les Turques-et-Ca&iuml;ques',
   'VG' => '&Icirc;les Vierges britanniques',
   'VI' => '&Icirc;les Vierges des &eacute;tats-Unis',
   'IN' => 'Inde',
   'ID' => 'Indon&eacute;sie',
   'IQ' => 'Irak',
   'IR' => 'Iran',
   'IE' => 'Irlande',
   'IS' => 'Islande',
   'IL' => 'Isra&euml;l',
   'IT' => 'Italie',
   'JM' => 'Jama&iuml;que',
   'JP' => 'Japon',
   'JE' => 'Jersey',
   'JO' => 'Jordanie',
   'KZ' => 'Kazakhstan',
   'KE' => 'Kenya',
   'KG' => 'Kirghizistan',
   'KI' => 'Kiribati',
   'XK' => 'Kosovo',
   'KW' => 'Kowe&iuml;t',
   'RE' => 'La R&eacute;union',
   'LA' => 'Laos',
   'LS' => 'Lesotho',
   'LV' => 'Lettonie',
   'LB' => 'Liban',
   'LR' => 'Lib&eacute;ria',
   'LY' => 'Libye',
   'LI' => 'Liechtenstein',
   'LT' => 'Lituanie',
   'LU' => 'Luxembourg',
   'MK' => 'Mac&eacute;doine',
   'MG' => 'Madagascar',
   'MY' => 'Malaisie',
   'MW' => 'Malawi',
   'MV' => 'Maldives',
   'ML' => 'Mali',
   'MT' => 'Malte',
   'MA' => 'Maroc',
   'MQ' => 'Martinique',
   'MU' => 'Maurice',
   'MR' => 'Mauritanie',
   'YT' => 'Mayotte',
   'MX' => 'Mexique',
   'MD' => 'Moldavie',
   'MC' => 'Monaco',
   'MN' => 'Mongolie',
   'ME' => 'Mont&eacute;n&eacute;gro',
   'MS' => 'Montserrat',
   'MZ' => 'Mozambique',
   'MM' => 'Myanmar',
   'NA' => 'Namibie',
   'NR' => 'Nauru',
   'NP' => 'N&eacute;pal',
   'NI' => 'Nicaragua',
   'NE' => 'Niger',
   'NG' => 'Nig&eacute;ria',
   'NU' => 'Niue',
   'NO' => 'Norv&egrave;ge',
   'NC' => 'Nouvelle-Cal&eacute;donie',
   'NZ' => 'Nouvelle-Z&eacute;lande',
   'OM' => 'Oman',
   'UG' => 'Ouganda',
   'UZ' => 'Ouzb&eacute;kistan',
   'PK' => 'Pakistan',
   'PW' => 'Palaos',
   'PA' => 'Panama',
   'PG' => 'Papouasie-Nouvelle-Guin&eacute;e',
   'PY' => 'Paraguay',
   'NL' => 'Pays-Bas',
   'BQ' => 'Pays-Bas carib&eacute;ens',
   'PE' => 'P&eacute;rou',
   'PH' => 'Philippines',
   'PN' => 'Pitcairn',
   'PL' => 'Pologne',
   'PF' => 'Polyn&eacute;sie fran&ccedil;aise',
   'PR' => 'Porto Rico',
   'PT' => 'Portugal',
   'QA' => 'Qatar',
   'HK' => 'R.A.S. chinoise de Hong Kong',
   'MO' => 'R.A.S. chinoise de Macao',
   'CF' => 'R&eacute;publique centrafricaine',
   'DO' => 'R&eacute;publique dominicaine',
   'CZ' => 'R&eacute;publique tch&egrave;que',
   'RO' => 'Roumanie',
   'GB' => 'Royaume-Uni',
   'RU' => 'Russie',
   'RW' => 'Rwanda',
   'EH' => 'Sahara occidental',
   'BL' => 'Saint-Barth&eacute;lemy',
   'KN' => 'Saint-Christophe-et-Ni&eacute;v&egrave;s',
   'SM' => 'Saint-Marin',
   'MF' => 'Saint-Martin (partie fran&ccedil;aise)',
   'SX' => 'Saint-Martin (partie n&eacute;erlandaise)',
   'PM' => 'Saint-Pierre-et-Miquelon',
   'VC' => 'Saint-Vincent-et-les-Grenadines',
   'SH' => 'Sainte-H&eacute;l&egrave;ne',
   'LC' => 'Sainte-Lucie',
   'WS' => 'Samoa',
   'AS' => 'Samoa am&eacute;ricaines',
   'ST' => 'Sao Tom&eacute;-et-Principe',
   'SN' => 'S&eacute;n&eacute;gal',
   'RS' => 'Serbie',
   'SC' => 'Seychelles',
   'SL' => 'Sierra Leone',
   'SG' => 'Singapour',
   'SK' => 'Slovaquie',
   'SI' => 'Slov&eacute;nie',
   'SO' => 'Somalie',
   'SD' => 'Soudan',
   'SS' => 'Soudan du Sud',
   'LK' => 'Sri Lanka',
   'SE' => 'Su&egrave;de',
   'CH' => 'Suisse',
   'SR' => 'Suriname',
   'SJ' => 'Svalbard et Jan Mayen',
   'SZ' => 'Swaziland',
   'SY' => 'Syrie',
   'TJ' => 'Tadjikistan',
   'TW' => 'Ta&iuml;wan',
   'TZ' => 'Tanzanie',
   'TD' => 'Tchad',
   'TF' => 'Terres australes fran&ccedil;aises',
   'IO' => 'Territoire britannique de l’oc&eacute;an Indien',
   'PS' => 'Territoires palestiniens',
   'TH' => 'Tha&iuml;lande',
   'TL' => 'Timor oriental',
   'TG' => 'Togo',
   'TK' => 'Tokelau',
   'TO' => 'Tonga',
   'TT' => 'Trinit&eacute;-et-Tobago',
   'TA' => 'Tristan da Cunha',
   'TN' => 'Tunisie',
   'TM' => 'Turkm&eacute;nistan',
   'TR' => 'Turquie',
   'TV' => 'Tuvalu',
   'UA' => 'Ukraine',
   'UY' => 'Uruguay',
   'VU' => 'Vanuatu',
   'VE' => 'Venezuela',
   'VN' => 'Vietnam',
   'WF' => 'Wallis-et-Futuna',
   'YE' => 'Y&eacute;men',
   'ZM' => 'Zambie',
   'ZW' => 'Zimbabwe',
 );
