<?php
/**
 * FormIt
 *
 * Copyright 2009-2012 by Shaun McCormick <shaun@modx.com>
 *
 * FormIt is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option) any
 * later version.
 *
 * FormIt is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * FormIt; if not, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA
 *
 * @package formit
 */
/**
 * Array of countries
 * @package formit
 */
return array(
    'AF' => 'Afghanistan',
    'AL' => 'Albania',
    'DZ' => 'Algeria',
    'AS' => 'Samoa Americane',
    'AD' => 'Andorra',
    'AO' => 'Angola',
    'AI' => 'Anguilla',
    'AQ' => 'Antartide',
    'AG' => 'Antigua e Barbuda',
    'AR' => 'Argentina',
    'AM' => 'Armenia',
    'AW' => 'Aruba',
    'AU' => 'Australia',
    'AT' => 'Austria',
    'AZ' => 'Azerbaijan',
    'BS' => 'Bahamas',
    'BH' => 'Bahrain',
    'BD' => 'Bangladesh',
    'BB' => 'Barbados',
    'BY' => 'Bielorussia',
    'BE' => 'Belgio',
    'BZ' => 'Belize',
    'BJ' => 'Benin',
    'BM' => 'Bermuda',
    'BT' => 'Bhutan',
    'BO' => 'Bolivia',
    'BA' => 'Bosnia Erzegovina',
    'BW' => 'Botswana',
    'BV' => 'Isola Bouvet',
    'BR' => 'Brasile',
    'IO' => 'Territorio britannico dell\'Oceano Indiano',
    'BN' => 'Brunei',
    'BG' => 'Bulgaria',
    'BF' => 'Burkina Faso',
    'BI' => 'Burundi',
    'KH' => 'Cambogia',
    'CM' => 'Camerun',
    'CA' => 'Canada',
    'CV' => 'Capo Verde',
    'KY' => 'Isole Cayman',
    'CF' => 'Repubblica Centrafricana',
    'TD' => 'Chad',
    'CL' => 'Cile',
    'CN' => 'Cina',
    'CX' => 'Isola di Natale',
    'CC' => 'Isole Cocos (Keeling)',
    'CO' => 'Colombia',
    'KM' => 'Comore',
    'CG' => 'Congo',
    'CD' => 'Repubblica Democratica del Congo',
    'CK' => 'Isole Cook',
    'CR' => 'Costa Rica',
    'CI' => 'Costa d\'Avorio',
    'HR' => 'Croazia',
    'CU' => 'Cuba',
    'CY' => 'Cipro',
    'CZ' => 'Repubblica Ceca',
    'DK' => 'Danimarca',
    'DJ' => 'Gibuti',
    'DM' => 'Dominica',
    'DO' => 'Repubblica Dominicana',
    'EC' => 'Ecuador',
    'EG' => 'Egitto',
    'SV' => 'El Salvador',
    'GQ' => 'Guinea Equatoriale',
    'ER' => 'Eritrea',
    'EE' => 'Estonia',
    'ET' => 'Etiopia',
    'FK' => 'Isole Falkland (Malvinas)',
    'FO' => 'Isole Faroe',
    'FJ' => 'Fiji',
    'FI' => 'Finlandia',
    'FR' => 'Francia',
    'GF' => 'Guyana francese',
    'PF' => 'Polinesia Francese',
    'TF' => 'Territori australi francesi',
    'GA' => 'Gabon',
    'GM' => 'Gambia',
    'GE' => 'Georgia',
    'DE' => 'Germania',
    'GH' => 'Ghana',
    'GI' => 'Gibilterra',
    'GR' => 'Grecia',
    'GL' => 'Groenlandia',
    'GD' => 'Grenada',
    'GP' => 'Guadalupa',
    'GU' => 'Guam',
    'GT' => 'Guatemala',
    'GN' => 'Guinea',
    'GW' => 'Guinea-Bissau',
    'GY' => 'Guyana',
    'HT' => 'Haiti',
    'HM' => 'Isola Heard e Isole McDonald',
    'VA' => 'Città del Vaticano',
    'HN' => 'Honduras',
    'HK' => 'Hong Kong',
    'HU' => 'Ungheria',
    'IS' => 'Islanda',
    'IN' => 'India',
    'ID' => 'Indonesia',
    'IR' => 'Iran',
    'IQ' => 'Iraq',
    'IE' => 'Irlanda',
    'IL' => 'Israele',
    'IT' => 'Italia',
    'JM' => 'Giamaica',
    'JP' => 'Giappone',
    'JO' => 'Giordania',
    'KZ' => 'Kazakistan',
    'KE' => 'Kenya',
    'KI' => 'Kiribati',
    'KP' => 'Repubblica Popolare Democratica di Corea',
    'KR' => 'Repubblica di Corea',
    'KW' => 'Kuwait',
    'KG' => 'Kirghizistan',
    'LA' => 'Laos',
    'LV' => 'Lettonia',
    'LB' => 'Libano',
    'LS' => 'Lesotho',
    'LR' => 'Liberia',
    'LY' => 'Libia',
    'LI' => 'Liechtenstein',
    'LT' => 'Lituania',
    'LU' => 'Lussemburgo',
    'MO' => 'Macao',
    'MK' => 'Macedonia',
    'MG' => 'Madagascar',
    'MW' => 'Malawi',
    'MY' => 'Malesia',
    'MV' => 'Maldive',
    'ML' => 'Mali',
    'MT' => 'Malta',
    'MH' => 'Isole Marshall',
    'MQ' => 'Martinica',
    'MR' => 'Mauritania',
    'MU' => 'Mauritius',
    'YT' => 'Mayotte',
    'MX' => 'Messico',
    'FM' => 'Stati Federati di Micronesia',
    'MD' => 'Moldavia',
    'MC' => 'Monaco',
    'MN' => 'Mongolia',
    'MS' => 'Montserrat',
    'MA' => 'Marocco',
    'MZ' => 'Mozambico',
    'MM' => 'Birmania',
    'NA' => 'Namibia',
    'NR' => 'Nauru',
    'NP' => 'Nepal',
    'NL' => 'Olanda',
    'AN' => 'Antille Olandesi',
    'NC' => 'Nuova Caledonia',
    'NZ' => 'Nuova Zelanda',
    'NI' => 'Nicaragua',
    'NE' => 'Niger',
    'NG' => 'Nigeria',
    'NU' => 'Niue',
    'NF' => 'Isola Norfolk',
    'MP' => 'Isole Marianne Settentrionali',
    'NO' => 'Norvegia',
    'OM' => 'Oman',
    'PK' => 'Pakistan',
    'PW' => 'Palau',
    'PS' => 'Territori palestinesi',
    'PA' => 'Panama',
    'PG' => 'Papua Nuova Guinea',
    'PY' => 'Paraguay',
    'PE' => 'Perù',
    'PH' => 'Filippine',
    'PN' => 'Isole Pitcairn',
    'PL' => 'Polonia',
    'PT' => 'Portogallo',
    'PR' => 'Porto Rico',
    'QA' => 'Qatar',
    'RE' => 'Riunione',
    'RO' => 'Romania',
    'RU' => 'Federazione Russa',
    'RW' => 'Ruanda',
    'SH' => 'Sant\'Elena',
    'KN' => 'Saint Kitts e Nevis',
    'LC' => 'Santa Lucia',
    'PM' => 'Saint-Pierre e Miquelon',
    'VC' => 'Saint Vincent e Grenadine',
    'WS' => 'Samoa',
    'SM' => 'San Marino',
    'ST' => 'São Tomé e Príncipe',
    'SA' => 'Arabia Saudita',
    'SN' => 'Senegal',
    'CS' => 'Serbia e Montenegro',
    'SC' => 'Seychelles',
    'SL' => 'Sierra Leone',
    'SG' => 'Singapore',
    'SK' => 'Slovacchia',
    'SI' => 'Slovenia',
    'SB' => 'Isole Solomon',
    'SO' => 'Somalia',
    'ZA' => 'Sud Africa',
    'GS' => 'Georgia del Sud e Sandwich Australi',
    'ES' => 'Spagna',
    'LK' => 'Sri Lanka',
    'SD' => 'Sudan',
    'SR' => 'Suriname',
    'SJ' => 'Svalbard e Jan Mayen',
    'SZ' => 'eSwatini',
    'SE' => 'Svezia',
    'CH' => 'Svizzera',
    'SY' => 'Siria',
    'TW' => 'Taiwan',
    'TJ' => 'Tagikistan',
    'TZ' => 'Tanzania',
    'TH' => 'Tailandia',
    'TL' => 'Timor Est',
    'TG' => 'Togo',
    'TK' => 'Tokelau',
    'TO' => 'Tonga',
    'TT' => 'Trinidad e Tobago',
    'TN' => 'Tunisia',
    'TR' => 'Turchia',
    'TM' => 'Turkmenistan',
    'TC' => 'Isole Turks e Caicos',
    'TV' => 'Tuvalu',
    'UG' => 'Uganda',
    'UA' => 'Ucraina',
    'AE' => 'Emirati Arabi Uniti',
    'GB' => 'Regno Unito',
    'US' => 'Stati Uniti',
    'UM' => 'Isole Minori Esterne degli Stati Uniti',
    'UY' => 'Uruguay',
    'UZ' => 'Uzbekistan',
    'VU' => 'Vanuatu',
    'VE' => 'Venezuela',
    'VN' => 'Vietnam',
    'VG' => 'Isole Vergini britanniche',
    'VI' => 'Isole Vergini Americane',
    'WF' => 'Wallis e Futuna',
    'EH' => 'Sahara Occidentale',
    'YE' => 'Yemen',
    'ZM' => 'Zambia',
    'ZW' => 'Zimbabwe',
);