<?php
/**
 * FormIt
 *
 * Copyright 2009-2012 by Shaun McCormick <shaun@modx.com>
 *
 * FormIt is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option) any
 * later version.
 *
 * FormIt is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * FormIt; if not, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA
 *
 * @package formit
 */
/**
 * Array of countries in Swedish
 * Source for country codes: http://www.iso.org/iso/home/standards/country_codes/country_names_and_code_elements.htm (2013-06-23)
 * @package formit
 */
return array(
    'AF' => 'Afghanistan',
    'AL' => 'Albanien',
    'DZ' => 'Algeriet',
    'VI' => 'Amerikanska Jungfru&ouml;arna',
    'AS' => 'Amerikanska Samoa',
    'AD' => 'Andorra',
    'AO' => 'Angola',
    'AI' => 'Anguilla',
    'AQ' => 'Antarktis',
    'AG' => 'Antigua och Barbuda',
    'AR' => 'Argentina',
    'AM' => 'Armenien',
    'AW' => 'Aruba',
    'AU' => 'Australien',
    'AZ' => 'Azerbajdzjan',
    'BS' => 'Bahamas',
    'BH' => 'Bahrain',
    'BD' => 'Bangladesh',
    'BB' => 'Barbados',
    'BE' => 'Belgien',
    'BZ' => 'Belize',
    'BJ' => 'Benin',
    'BM' => 'Bermuda',
    'BT' => 'Bhutan',
    'BO' => 'Bolivia, M&aring;ngnationella staten',
    'BQ' => 'Bonaire, Sint Eustatius och Saba',
    'BA' => 'Bosnien-Hercegovina',
    'BW' => 'Botswana',
    'BV' => 'Bouvet&ouml;n',
    'BR' => 'Brasilien',
    'VG' => 'Brittiska Jungfru&ouml;arna',
    'IO' => 'Brittiska territoriet i Indiska oceanen',
    'BN' => 'Brunei Darussalam',
    'BG' => 'Bulgarien',
    'BF' => 'Burkina Faso',
    'BI' => 'Burundi',
    'KY' => 'Cayman&ouml;arna',
    'CF' => 'Centralafrikanska republiken',
    'TD' => 'Chad',
    'CL' => 'Chile',
    'CO' => 'Colombia',
    'KM' => 'Comoros',
    'CK' => 'Cook&ouml;arna',
    'CR' => 'Costa Rica',
    'CW' => 'Cura&ccedil;ao',
    'CY' => 'Cypern',
    'DK' => 'Danmark',
    'DJ' => 'Djibouti',
    'DM' => 'Dominica',
    'DO' => 'Dominikanska republiken',
    'EC' => 'Ecuador',
    'EG' => 'Egypten',
    'GQ' => 'Ekvatorialguinea',
    'SV' => 'El Salvador',
    'CI' => 'Elfenbenskusten',
    'ER' => 'Eritrea',
    'EE' => 'Estland',
    'ET' => 'Etiopien',
    'FK' => 'Falklands&ouml;arna',
    'FJ' => 'Fiji',
    'PH' => 'Filippinerna',
    'FI' => 'Finland',
    'FR' => 'Frankrike',
    'GF' => 'Franska Guyana',
    'PF' => 'Franska Polynesien',
    'TF' => 'Franska syd- och Antarktisterritorier',
    'FO' => 'F&auml;r&ouml;arna',
    'AE' => 'F&ouml;renade arabemiraten',
    'UM' => 'F&ouml;renta staternas avl&auml;gset bel&auml;gna &ouml;ar',
    'GA' => 'Gabon',
    'GM' => 'Gambia',
    'GE' => 'Georgien',
    'GH' => 'Ghana',
    'GI' => 'Gibraltar',
    'GR' => 'Grekland',
    'GD' => 'Grenada',
    'GL' => 'Gr&ouml;nland',
    'GP' => 'Guadeloupe',
    'GU' => 'Guam',
    'GT' => 'Guatemala',
    'GG' => 'Guernsey',
    'GN' => 'Guinea',
    'GW' => 'Guinea-Bissau',
    'GY' => 'Guyana',
    'HT' => 'Haiti',
    'HM' => 'Heard&ouml;n och McDonalds&ouml;arna',
    'HN' => 'Honduras',
    'HK' => 'Hong Kong',
    'IN' => 'Indien',
    'ID' => 'Indonesien',
    'IQ' => 'Irak',
    'IR' => 'Iran, Islamiska republiken',
    'IE' => 'Irland',
    'IS' => 'Island',
    'IM' => 'Isle of Man',
    'IL' => 'Israel',
    'IT' => 'Italien',
    'JM' => 'Jamaica',
    'JP' => 'Japan',
    'JE' => 'Jersey',
    'JO' => 'Jordanien',
    'CX' => 'Jul&ouml;n',
    'KH' => 'Kambodja',
    'CM' => 'Kamerun',
    'CA' => 'Kanada',
    'CV' => 'Kap Verde',
    'KZ' => 'Kazakstan',
    'KE' => 'Kenya',
    'CN' => 'Kina',
    'KG' => 'Kirgizistan',
    'KI' => 'Kiribati',
    'CC' => 'Kokos&ouml;arna',
    'CD' => 'Kongo, Demokratiska republiken',
    'CG' => 'Kongo, Republiken',
    'KP' => 'Korea, Demokratiska folkrepubliken',
    'KR' => 'Korea, Republiken',
    'HR' => 'Kroatien',
    'CU' => 'Kuba',
    'KW' => 'Kuwait',
    'LA' => 'Laos, Demokratiska folkrepubliken',
    'LS' => 'Lesotho',
    'LV' => 'Lettland',
    'LB' => 'Libanon',
    'LR' => 'Liberia',
    'LY' => 'Libyen',
    'LI' => 'Liechtenstein',
    'LT' => 'Litauen',
    'LU' => 'Luxemburg',
    'MO' => 'Macao',
    'MG' => 'Madagaskar',
    'MK' => 'Makedonien, Republiken',
    'MW' => 'Malawi',
    'MY' => 'Malaysia',
    'MV' => 'Maldiverna',
    'ML' => 'Mali',
    'MT' => 'Malta',
    'MA' => 'Marocko',
    'MH' => 'Marshall&ouml;arna',
    'MQ' => 'Martinique',
    'MR' => 'Mauretanien',
    'MU' => 'Mauritius',
    'YT' => 'Mayotte',
    'MX' => 'Mexiko',
    'FM' => 'Mikronesiska federationen',
    'MD' => 'Moldavien, Republiken',
    'MC' => 'Monaco',
    'MN' => 'Mongoliet',
    'ME' => 'Montenegro',
    'MS' => 'Montserrat',
    'MZ' => 'Mozambique',
    'MM' => 'Myanmar',
    'NA' => 'Namibia',
    'NR' => 'Nauru',
    'NL' => 'Nederl&auml;nderna',
    'NP' => 'Nepal',
    'NI' => 'Nicaragua',
    'NE' => 'Niger',
    'NG' => 'Nigeria',
    'NU' => 'Niue',
    'MP' => 'Nordmarianerna',
    'NF' => 'Norfolk Island',
    'NO' => 'Norge',
    'NC' => 'Nya Kaledonien',
    'NZ' => 'Nya Zeeland',
    'OM' => 'Oman',
    'PK' => 'Pakistan',
    'PW' => 'Palau',
    'PS' => 'Palestina',
    'PA' => 'Panama',
    'PG' => 'Papua Nya Guinea',
    'PY' => 'Paraguay',
    'PE' => 'Peru',
    'PN' => 'Pitcairn',
    'PL' => 'Polen',
    'PT' => 'Portugal',
    'PR' => 'Puerto Rico',
    'QA' => 'Qatar',
    'RE' => 'Reunion',
    'RO' => 'Rum&auml;nien',
    'RW' => 'Rwanda',
    'RU' => 'Ryska federationen',
    'BL' => 'Saint Barth&eacute;lemy',
    'SH' => 'Saint Helena, Ascension och Tristan da Cunha',
    'KN' => 'Saint Kitts och Nevis',
    'LC' => 'Saint Lucia',
    'MF' => 'Saint Martin (Franska delen)',
    'VC' => 'Saint Vincent och Grenadinerna',
    'PM' => 'Saint-Pierre och Miquelon',
    'SB' => 'Salomon&ouml;arna',
    'WS' => 'Samoa',
    'SM' => 'San Marino',
    'ST' => 'Sao Tome och Principe',
    'SA' => 'Saudiarabien',
    'CH' => 'Schweiz',
    'SN' => 'Senegal',
    'RS' => 'Serbien',
    'SC' => 'Seychellerna',
    'SL' => 'Sierra Leone',
    'SG' => 'Singapore',
    'SX' => 'Sint Maarten (nederl&auml;ndska delen)',
    'SK' => 'Slovakien',
    'SI' => 'Slovenien',
    'SO' => 'Somalia',
    'ES' => 'Spanien',
    'LK' => 'Sri Lanka',
    'GB' => 'Storbritannien',
    'SD' => 'Sudan',
    'SR' => 'Surinam',
    'SJ' => 'Svalbard och Jan Mayen',
    'SZ' => 'Swaziland',
    'SE' => 'Sverige',
    'ZA' => 'Sydafrika',
    'GS' => 'Sydgeorgien och Sydsandwich&ouml;arna',
    'SS' => 'Sydsudan',
    'SY' => 'Syrien, Arabrepubliken',
    'TJ' => 'Tadzjikistan',
    'TW' => 'Taiwan',
    'TZ' => 'Tanzania, F&ouml;renade republiken',
    'TH' => 'Thailand',
    'CZ' => 'Tjeckien, Republiken',
    'TG' => 'Togo',
    'TK' => 'Tokelau&ouml;arna',
    'TO' => 'Tonga',
    'TT' => 'Trinidad och Tobago',
    'TN' => 'Tunisien',
    'TR' => 'Turkiet',
    'TM' => 'Turkmenistan',
    'TC' => 'Turks- och Caicos&ouml;arna',
    'TV' => 'Tuvalu',
    'DE' => 'Tyskland',
    'UG' => 'Uganda',
    'UA' => 'Ukraina',
    'HU' => 'Ungern',
    'UY' => 'Uruguay',
    'US' => 'USA',
    'UZ' => 'Uzbekistan',
    'WF' => 'Wallis- och Futuna&ouml;arna',
    'VU' => 'Vanuatu',
    'VA' => 'Vatikanstaten',
    'VE' => 'Venezuela, Bolivarianska republiken',
    'VN' => 'Vietnam',
    'BY' => 'Vitryssland',
    'EH' => 'V&auml;stsahara',
    'YE' => 'Yemen',
    'ZM' => 'Zambia',
    'ZW' => 'Zimbabwe',
    'AX' => '&Aring;land',
    'AT' => '&Ouml;sterrike',
    'TL' => '&Ouml;sttimor'
);