<?php
/**
 * FormIt
 *
 * Copyright 2009-2012 by Shaun McCormick <shaun@modx.com>
 *
 * FormIt is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option) any
 * later version.
 *
 * FormIt is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * FormIt; if not, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA
 *
 * @package formit
 */
/**
 * Array of countries
 * @package formit
 * @author Jelle Maes at vids-and-bits.be <info@vids-and-bits.be>
 */
return array(
		'AF' => 'Afghanistan',
		'AL' => 'Albani&euml;',
		'DZ' => 'Algerije',
		'VI' => 'Amerikaanse Maagdeneilanden',
		'AS' => 'Amerikaans-Samoa',
		'AD' => 'Andorra',
		'AO' => 'Angola',
		'AI' => 'Anguilla',
		'AQ' => 'Antarctica',
		'AG' => 'Antigua en Barbuda',
		'AR' => 'Argentini&euml;',
		'AM' => 'Armeni&euml;',
		'AW' => 'Aruba',
		'AU' => 'Australi&euml;',
		'AZ' => 'Azerbeidzjan',
		'BS' => 'Bahamas',
		'BH' => 'Bahrein',
		'BD' => 'Bangladesh',
		'BB' => 'Barbados',
		'BE' => 'Belgi&euml;',
		'BZ' => 'Belize',
		'BJ' => 'Benin',
		'BM' => 'Bermuda',
		'PS' => 'Bezette Palestijnse gebieden',
		'BT' => 'Bhutan',
		'BO' => 'Bolivi&euml;',
		'BQ' => 'Bonaire, Sint-Eustatius en Saba',
		'BA' => 'Bosni&euml; en Herzegovina',
		'BW' => 'Botswana',
		'BV' => 'Bouveteiland',
		'BR' => 'Brazili&euml;',
		'IO' => 'Brits Indische oceaan',
		'VG' => 'Britse Maagdeneilanden',
		'BN' => 'Brunei Darussalam',
		'BG' => 'Bulgarije',
		'BF' => 'Burkina Faso',
		'BI' => 'Burundi',
		'KH' => 'Cambodja',
		'CA' => 'Canada',
		'KY' => 'Caymaneilanden',
		'CF' => 'Centraal-Afrika',
		'CL' => 'Chili',
		'CN' => 'China',
		'CX' => 'Christmaseiland',
		'CC' => 'Cocos- (Keeling-) eilanden',
		'CO' => 'Colombia',
		'KM' => 'Comoren',
		'CD' => 'Congo',
		'CG' => 'Congo',
		'CK' => 'Cookeilanden',
		'CR' => 'Costa Rica',
		'CU' => 'Cuba',
		'CW' => 'Curaçao',
		'CY' => 'Cyprus',
		'DK' => 'Denemarken',
		'DJ' => 'Djibouti',
		'DM' => 'Dominica',
		'DO' => 'Dominicaanse Republiek',
		'DE' => 'Duitsland',
		'EC' => 'Ecuador',
		'EG' => 'Egypte',
		'IM' => 'Eiland Man',
		'SV' => 'El Salvador',
		'GQ' => 'Equatoriaal-Guinea',
		'ER' => 'Eritrea',
		'EE' => 'Estland',
		'ET' => 'Ethiopi&euml;',
		'FO' => 'Faer&ouml;ereilanden',
		'FK' => 'Falklandeilanden (Malvinas)',
		'FJ' => 'Fiji',
		'PH' => 'Filipijnen',
		'FI' => 'Finland',
		'FR' => 'Frankrijk',
		'TF' => 'Franse zuidelijke gebieden',
		'GF' => 'Frans-Guyana',
		'PF' => 'Frans-Polynesi&euml;',
		'GA' => 'Gabon',
		'GM' => 'Gambia',
		'GE' => 'Georgi&euml;',
		'GH' => 'Ghana',
		'GI' => 'Gibraltar',
		'GD' => 'Grenada',
		'GR' => 'Griekenland',
		'GL' => 'Groenland',
		'GP' => 'Guadeloupe',
		'GU' => 'Guam',
		'GT' => 'Guatemala',
		'GG' => 'Guernsey',
		'GN' => 'Guinea',
		'GW' => 'Guinee-Bissau',
		'GY' => 'Guyana',
		'HT' => 'Ha&iuml;ti',
		'HM' => 'Heard- en McDonaldeilanden',
		'VA' => 'Heilige stoel',
		'HN' => 'Honduras',
		'HU' => 'Hongarije',
		'HK' => 'Hongkong',
		'IE' => 'Ierland',
		'IS' => 'Ijsland',
		'IN' => 'India',
		'ID' => 'Indonesi&euml;',
		'IQ' => 'Irak',
		'IR' => 'Iran',
		'IL' => 'Isra&euml;l',
		'IT' => 'Itali&euml;',
		'CI' => 'Ivoorkust',
		'JM' => 'Jamaica',
		'JP' => 'Japan',
		'YE' => 'Jemen',
		'JE' => 'Jersey',
		'JO' => 'Jordani&euml;',
		'CV' => 'Kaapverdi&euml;',
		'CM' => 'Kameroen',
		'KZ' => 'Kazachstan',
		'KE' => 'Kenia',
		'KG' => 'Kirgistan',
		'KI' => 'Kiribati',
		'UM' => 'Kleine afgelegen eilanden van de Verenigde Staten',
		'KW' => 'Koeweit',
		'HR' => 'Kroati&euml;',
		'LA' => 'Laos',
		'LS' => 'Lesotho',
		'LV' => 'Letland',
		'LB' => 'Libanon',
		'LR' => 'Liberia',
		'LY' => 'Libi&euml;',
		'LI' => 'Liechtenstein',
		'LT' => 'Litouwen',
		'LU' => 'Luxemburg',
		'MO' => 'Macao',
		'MK' => 'Macedoni&euml;',
		'MG' => 'Madagascar',
		'MW' => 'Malawi',
		'MV' => 'Maldiven',
		'MY' => 'Maleisi&euml;',
		'ML' => 'Mali',
		'MT' => 'Malta',
		'MA' => 'Marokko',
		'MH' => 'Marshalleilanden',
		'MQ' => 'Martinique',
		'MR' => 'Mauritani&euml;',
		'MU' => 'Mauritius',
		'YT' => 'Mayotte',
		'MX' => 'Mexico',
		'FM' => 'Micronesi&euml;',
		'MD' => 'Moldavi&euml;',
		'MC' => 'Monaco',
		'MN' => 'Mongoli&euml;',
		'ME' => 'Montenegro',
		'MS' => 'Montserrat',
		'MZ' => 'Mozambique',
		'MM' => 'Myanmar',
		'NA' => 'Namibi&euml;',
		'NR' => 'Nauru',
		'NL' => 'Nederland',
		'NP' => 'Nepal',
		'NI' => 'Nicaragua',
		'NC' => 'Nieuw-Caledoni&euml;',
		'NZ' => 'Nieuw-Zeeland',
		'NE' => 'Niger',
		'NG' => 'Nigeria',
		'NU' => 'Niue',
		'MP' => 'Noordelijke Marianen',
		'KP' => 'Noord-Korea',
		'NO' => 'Noorwegen',
		'NF' => 'Norfolkeiland',
		'UG' => 'Oeganda',
		'UA' => 'Oekra&iuml;ne',
		'UZ' => 'Oezbekistan',
		'OM' => 'Oman',
		'AT' => 'Oostenrijk',
		'TL' => 'Oost-Timor',
		'PK' => 'Pakistan',
		'PW' => 'Palau',
		'PA' => 'Panama',
		'PG' => 'Papoea-Nieuw-Guinea',
		'PY' => 'Paraguay',
		'PE' => 'Peru',
		'PN' => 'Pitcairn',
		'PL' => 'Polen',
		'PT' => 'Portugal',
		'PR' => 'Puerto Rico',
		'QA' => 'Qatar',
		'RE' => 'R&eacute;union',
		'RO' => 'Roemeni&euml;',
		'RU' => 'Rusland',
		'RW' => 'Rwanda',
		'KN' => 'Saint Kitts en Nevis',
		'VC' => 'Saint Vincent en de Grenadines',
		'BL' => 'Saint-Barth&eacute;lemy',
		'PM' => 'Saint-Pierre en Miquelon',
		'SB' => 'Salomonseilanden',
		'WS' => 'Samoa',
		'SM' => 'San Marino',
		'ST' => 'S&atilde;o Tom&eacute; en Príncipe',
		'SA' => 'Saoedi-Arabi&euml;',
		'SN' => 'Senegal',
		'RS' => 'Servi&euml;',
		'SC' => 'Seychellen',
		'SL' => 'Sierra Leone',
		'SG' => 'Singapore',
		'SH' => 'Sint Helena, Ascension en Tristan da Cunha',
		'LC' => 'Sint Lucia',
		'MF' => 'Sint Maarten (Frans deel)',
		'SX' => 'Sint Maarten (Nederlands deel)',
		'SI' => 'Sloveni&euml;',
		'SK' => 'Slowakije',
		'SD' => 'Soedan',
		'SO' => 'Somali&euml;',
		'ES' => 'Spanje',
		'LK' => 'Sri Lanka',
		'SR' => 'Suriname',
		'SJ' => 'Svalbard en Jan Mayen',
		'SZ' => 'Swaziland',
		'SY' => 'Syri&euml;',
		'TJ' => 'Tadzjikistan',
		'TW' => 'Taiwan, Chinese provincie',
		'TZ' => 'Tanzani&euml;',
		'TH' => 'Thailand',
		'TG' => 'Togo',
		'TK' => 'Tokelau',
		'TO' => 'Tonga',
		'TT' => 'Trinidad en Tobago',
		'TD' => 'Tsjaad',
		'CZ' => 'Tsjechi&euml;',
		'TN' => 'Tunesi&euml;',
		'TR' => 'Turkije',
		'TM' => 'Turkmenistan',
		'TC' => 'Turks- en Caicoseilanden',
		'TV' => 'Tuvalu',
		'UY' => 'Uruguay',
		'VU' => 'Vanuatu',
		'VE' => 'Venezuela',
		'GB' => 'Verenigd Koninkrijk',
		'AE' => 'Verenigde Arabische Emiraten',
		'US' => 'Verenigde Staten',
		'VN' => 'Vietnam',
		'WF' => 'Wallis en Futuna',
		'EH' => 'Westelijke Sahara',
		'BY' => 'Wit-Rusland',
		'ZM' => 'Zambia',
		'ZW' => 'Zimbabwe',
		'KR' => 'Zuid Korea',
		'ZA' => 'Zuid-Afrika',
		'GS' => 'Zuid-Georgi&euml; en de Zuid-Sandwicheilanden',
		'SS' => 'Zuid-Soedan',
		'SE' => 'Zweden',
		'CH' => 'Zwitserland'
);
